// <auto-generated />
using LocalBusiness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusiness.Migrations
{
    [DbContext(typeof(LocalBusinessContext))]
    [Migration("20220423032056_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Category")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Zip")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Address = "3106 SE Hawthorne Blvd",
                            Category = "Food & Drink",
                            City = "Portland",
                            Description = "Cuban joint serves up homestyle fare plus cocktails in casual, vibrant surrounds with a patio.",
                            Name = "Cubo",
                            Phone = "(971) 544-7801",
                            State = "OR",
                            Zip = "97214"
                        },
                        new
                        {
                            BusinessId = 2,
                            Address = "1801 NE Cesar E Chavez Blvd",
                            Category = "Food & Drink",
                            City = "Portland",
                            Description = "Asian fusion dishes in quaint surrounds",
                            Name = "Gado Gado",
                            Phone = "(503) 206-8778",
                            State = "OR",
                            Zip = "97212"
                        },
                        new
                        {
                            BusinessId = 3,
                            Address = "1005 W Burnside St",
                            Category = "Retail",
                            City = "Portland",
                            Description = "Iconic bookstore occupying a city block",
                            Name = "Powell's City of Books",
                            Phone = "(971) 544-7801",
                            State = "OR",
                            Zip = "97214"
                        },
                        new
                        {
                            BusinessId = 4,
                            Address = "4122 NE Sandy Blvd",
                            Category = "Entertainment",
                            City = "Portland",
                            Description = "Historic movie house showing indie films.",
                            Name = "Hollywood Theatre",
                            Phone = "(503) 493-1128",
                            State = "OR",
                            Zip = "97212"
                        },
                        new
                        {
                            BusinessId = 5,
                            Address = "3939 N Mississippi Ave",
                            Category = "Entertainment",
                            City = "Portland",
                            Description = "A restored church houses this intimate live music spot",
                            Name = "Mississippi Studios",
                            Phone = "(503) 288-3895",
                            State = "OR",
                            Zip = "97227"
                        },
                        new
                        {
                            BusinessId = 6,
                            Address = "6006 E Burnside St",
                            Category = "Service",
                            City = "Portland",
                            Description = "Auto body shop.",
                            Name = "K&H Auto Shop",
                            Phone = "(971) 300-8228",
                            State = "OR",
                            Zip = "97215"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
